version: '2'
services:
  web:
    image: odoo:10.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=myodoouser
    - PASSWORD=myodoopassword
    volumes:
      - ./stack/odoo:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    links:
      - mydb:mydb
  mydb:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=myodoouser
      - POSTGRES_PASSWORD=myodoopassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./stack/postgres:/var/lib/postgresql/data/pgdata